# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jnaylor/code/testing/basic_renderer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jnaylor/code/testing/basic_renderer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jnaylor/code/testing/basic_renderer/CMakeFiles /home/jnaylor/code/testing/basic_renderer//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jnaylor/code/testing/basic_renderer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named flatland_nerf

# Build rule for target.
flatland_nerf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 flatland_nerf
.PHONY : flatland_nerf

# fast build rule for target.
flatland_nerf/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flatland_nerf.dir/build.make CMakeFiles/flatland_nerf.dir/build
.PHONY : flatland_nerf/fast

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flatland_nerf.dir/build.make CMakeFiles/flatland_nerf.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flatland_nerf.dir/build.make CMakeFiles/flatland_nerf.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flatland_nerf.dir/build.make CMakeFiles/flatland_nerf.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/utils/Camera.o: src/utils/Camera.cpp.o
.PHONY : src/utils/Camera.o

# target to build an object file
src/utils/Camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flatland_nerf.dir/build.make CMakeFiles/flatland_nerf.dir/src/utils/Camera.cpp.o
.PHONY : src/utils/Camera.cpp.o

src/utils/Camera.i: src/utils/Camera.cpp.i
.PHONY : src/utils/Camera.i

# target to preprocess a source file
src/utils/Camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flatland_nerf.dir/build.make CMakeFiles/flatland_nerf.dir/src/utils/Camera.cpp.i
.PHONY : src/utils/Camera.cpp.i

src/utils/Camera.s: src/utils/Camera.cpp.s
.PHONY : src/utils/Camera.s

# target to generate assembly for a file
src/utils/Camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flatland_nerf.dir/build.make CMakeFiles/flatland_nerf.dir/src/utils/Camera.cpp.s
.PHONY : src/utils/Camera.cpp.s

src/utils/CameraCal.o: src/utils/CameraCal.cpp.o
.PHONY : src/utils/CameraCal.o

# target to build an object file
src/utils/CameraCal.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flatland_nerf.dir/build.make CMakeFiles/flatland_nerf.dir/src/utils/CameraCal.cpp.o
.PHONY : src/utils/CameraCal.cpp.o

src/utils/CameraCal.i: src/utils/CameraCal.cpp.i
.PHONY : src/utils/CameraCal.i

# target to preprocess a source file
src/utils/CameraCal.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flatland_nerf.dir/build.make CMakeFiles/flatland_nerf.dir/src/utils/CameraCal.cpp.i
.PHONY : src/utils/CameraCal.cpp.i

src/utils/CameraCal.s: src/utils/CameraCal.cpp.s
.PHONY : src/utils/CameraCal.s

# target to generate assembly for a file
src/utils/CameraCal.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flatland_nerf.dir/build.make CMakeFiles/flatland_nerf.dir/src/utils/CameraCal.cpp.s
.PHONY : src/utils/CameraCal.cpp.s

src/utils/CameraOps.o: src/utils/CameraOps.cpp.o
.PHONY : src/utils/CameraOps.o

# target to build an object file
src/utils/CameraOps.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flatland_nerf.dir/build.make CMakeFiles/flatland_nerf.dir/src/utils/CameraOps.cpp.o
.PHONY : src/utils/CameraOps.cpp.o

src/utils/CameraOps.i: src/utils/CameraOps.cpp.i
.PHONY : src/utils/CameraOps.i

# target to preprocess a source file
src/utils/CameraOps.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flatland_nerf.dir/build.make CMakeFiles/flatland_nerf.dir/src/utils/CameraOps.cpp.i
.PHONY : src/utils/CameraOps.cpp.i

src/utils/CameraOps.s: src/utils/CameraOps.cpp.s
.PHONY : src/utils/CameraOps.s

# target to generate assembly for a file
src/utils/CameraOps.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flatland_nerf.dir/build.make CMakeFiles/flatland_nerf.dir/src/utils/CameraOps.cpp.s
.PHONY : src/utils/CameraOps.cpp.s

src/utils/CameraSimulator.o: src/utils/CameraSimulator.cpp.o
.PHONY : src/utils/CameraSimulator.o

# target to build an object file
src/utils/CameraSimulator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flatland_nerf.dir/build.make CMakeFiles/flatland_nerf.dir/src/utils/CameraSimulator.cpp.o
.PHONY : src/utils/CameraSimulator.cpp.o

src/utils/CameraSimulator.i: src/utils/CameraSimulator.cpp.i
.PHONY : src/utils/CameraSimulator.i

# target to preprocess a source file
src/utils/CameraSimulator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flatland_nerf.dir/build.make CMakeFiles/flatland_nerf.dir/src/utils/CameraSimulator.cpp.i
.PHONY : src/utils/CameraSimulator.cpp.i

src/utils/CameraSimulator.s: src/utils/CameraSimulator.cpp.s
.PHONY : src/utils/CameraSimulator.s

# target to generate assembly for a file
src/utils/CameraSimulator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flatland_nerf.dir/build.make CMakeFiles/flatland_nerf.dir/src/utils/CameraSimulator.cpp.s
.PHONY : src/utils/CameraSimulator.cpp.s

src/utils/Light.o: src/utils/Light.cpp.o
.PHONY : src/utils/Light.o

# target to build an object file
src/utils/Light.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flatland_nerf.dir/build.make CMakeFiles/flatland_nerf.dir/src/utils/Light.cpp.o
.PHONY : src/utils/Light.cpp.o

src/utils/Light.i: src/utils/Light.cpp.i
.PHONY : src/utils/Light.i

# target to preprocess a source file
src/utils/Light.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flatland_nerf.dir/build.make CMakeFiles/flatland_nerf.dir/src/utils/Light.cpp.i
.PHONY : src/utils/Light.cpp.i

src/utils/Light.s: src/utils/Light.cpp.s
.PHONY : src/utils/Light.s

# target to generate assembly for a file
src/utils/Light.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flatland_nerf.dir/build.make CMakeFiles/flatland_nerf.dir/src/utils/Light.cpp.s
.PHONY : src/utils/Light.cpp.s

src/utils/Ray.o: src/utils/Ray.cpp.o
.PHONY : src/utils/Ray.o

# target to build an object file
src/utils/Ray.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flatland_nerf.dir/build.make CMakeFiles/flatland_nerf.dir/src/utils/Ray.cpp.o
.PHONY : src/utils/Ray.cpp.o

src/utils/Ray.i: src/utils/Ray.cpp.i
.PHONY : src/utils/Ray.i

# target to preprocess a source file
src/utils/Ray.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flatland_nerf.dir/build.make CMakeFiles/flatland_nerf.dir/src/utils/Ray.cpp.i
.PHONY : src/utils/Ray.cpp.i

src/utils/Ray.s: src/utils/Ray.cpp.s
.PHONY : src/utils/Ray.s

# target to generate assembly for a file
src/utils/Ray.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flatland_nerf.dir/build.make CMakeFiles/flatland_nerf.dir/src/utils/Ray.cpp.s
.PHONY : src/utils/Ray.cpp.s

src/utils/Renderer.o: src/utils/Renderer.cpp.o
.PHONY : src/utils/Renderer.o

# target to build an object file
src/utils/Renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flatland_nerf.dir/build.make CMakeFiles/flatland_nerf.dir/src/utils/Renderer.cpp.o
.PHONY : src/utils/Renderer.cpp.o

src/utils/Renderer.i: src/utils/Renderer.cpp.i
.PHONY : src/utils/Renderer.i

# target to preprocess a source file
src/utils/Renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flatland_nerf.dir/build.make CMakeFiles/flatland_nerf.dir/src/utils/Renderer.cpp.i
.PHONY : src/utils/Renderer.cpp.i

src/utils/Renderer.s: src/utils/Renderer.cpp.s
.PHONY : src/utils/Renderer.s

# target to generate assembly for a file
src/utils/Renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flatland_nerf.dir/build.make CMakeFiles/flatland_nerf.dir/src/utils/Renderer.cpp.s
.PHONY : src/utils/Renderer.cpp.s

src/utils/SceneObject.o: src/utils/SceneObject.cpp.o
.PHONY : src/utils/SceneObject.o

# target to build an object file
src/utils/SceneObject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flatland_nerf.dir/build.make CMakeFiles/flatland_nerf.dir/src/utils/SceneObject.cpp.o
.PHONY : src/utils/SceneObject.cpp.o

src/utils/SceneObject.i: src/utils/SceneObject.cpp.i
.PHONY : src/utils/SceneObject.i

# target to preprocess a source file
src/utils/SceneObject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flatland_nerf.dir/build.make CMakeFiles/flatland_nerf.dir/src/utils/SceneObject.cpp.i
.PHONY : src/utils/SceneObject.cpp.i

src/utils/SceneObject.s: src/utils/SceneObject.cpp.s
.PHONY : src/utils/SceneObject.s

# target to generate assembly for a file
src/utils/SceneObject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flatland_nerf.dir/build.make CMakeFiles/flatland_nerf.dir/src/utils/SceneObject.cpp.s
.PHONY : src/utils/SceneObject.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... flatland_nerf"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/utils/Camera.o"
	@echo "... src/utils/Camera.i"
	@echo "... src/utils/Camera.s"
	@echo "... src/utils/CameraCal.o"
	@echo "... src/utils/CameraCal.i"
	@echo "... src/utils/CameraCal.s"
	@echo "... src/utils/CameraOps.o"
	@echo "... src/utils/CameraOps.i"
	@echo "... src/utils/CameraOps.s"
	@echo "... src/utils/CameraSimulator.o"
	@echo "... src/utils/CameraSimulator.i"
	@echo "... src/utils/CameraSimulator.s"
	@echo "... src/utils/Light.o"
	@echo "... src/utils/Light.i"
	@echo "... src/utils/Light.s"
	@echo "... src/utils/Ray.o"
	@echo "... src/utils/Ray.i"
	@echo "... src/utils/Ray.s"
	@echo "... src/utils/Renderer.o"
	@echo "... src/utils/Renderer.i"
	@echo "... src/utils/Renderer.s"
	@echo "... src/utils/SceneObject.o"
	@echo "... src/utils/SceneObject.i"
	@echo "... src/utils/SceneObject.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

